import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Holy Family Station",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/holy-family-station.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://ice7.securenetsystems.net/WVHF",
            active: true,
        },
        {
            name:"WDMC 920 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wdmc-920-am.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://wdmc.stream.miriamtech.net:8000/wdmc.mp3",
            active: false,
        },
        {
            name:"KHOJ Covenant Network 1460 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/khoj-covenant-network-1460-am.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://covenantnet.stream.miriamtech.net:8000/stream",
            active: false,
        },
        {
            name:"WLTQ 730 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wltq-730-am.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://streamingv2.shoutcast.com/catholicradiosc",
            active: false,
        },
        {
            name:"WQOM 1060 Catholic Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wqom-1060.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://hfc.streamguys1.com/wqom",
            active: false,
        },
        {
            name:"WLOF The Station of the Cross",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wlof-the-station-of-the-cross.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://hfc.streamguys1.com/wqom",
            active: false,
        },
        {
            name:"WYNW RELEVANT RADIO 92.9 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wynw-relevant-radio-92.9-fm.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://playerservices.streamtheworld.com/api/livestream-redirect/RR_MAIN.mp3",
            active: false,
        },
        {
            name:"WBVM Spirit FM 90.5",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wbvm-spirit-fm-90.5.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "http://spirit-fm.streamguys1.com/spiritfm",
            active: false,
        },        
         {
            name:"Radio Catolica Cincinnati",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radio-catolica-cincinnati.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://cloudstream2032.conectarhosting.com/8310/stream",
            active: false,
        },
        {
            name:"KSFV-CD Guadalupe Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/ksfv-cd-guadalupe-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://guadaluperadio.digital:2020/stream/AudioLiveGR",
            active: false,
        },
        {
            name:"WILB Living Bread Radio Network",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wilb-living-bread-radio-network.jpeg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://ic2.nwrnetwork.com/wilb-am",
            active: false,
        },
        {
            name:"KHSS Global Catholic Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/khss-global-catholic-radio.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://72.10.11.222:8813/broadwave.mp3",
            active: false,
        },
        {
            name:"KBVM Catholic Radio 88.3 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kbvm-catholic-radio-88.3-fm.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://147.135.84.28/kbvm-fm",
            active: false,
        },
        {
            name:"RadioFeCa",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radiofeca-senal-del-cielo.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://stream.xmission.com:8000/radiofeca",
            active: false,
        },
        {
            name:"Radio Paz WACC 830 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radio-paz-wacc-830-am.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://securestreams4.autopo.st:1576/pax",
            active: false,
        },
        {
            name:"EWTN Radio Catolica Mundial",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/ewtn-radio.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ewtn-ice.streamguys1.com/english-aac",
            active: false,
        },
        {
            name:"WHRQ Annunciation Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/whrq-annunciation-radio.jpeg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://ic2.nwrnetwork.com/annunciationradio",
            active: false,
        },
        {
            name:"Catolica Springfield 102.5 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/catolica-springfield-102.5-fm.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ais-edge37-live365-dal02.cdnstream.com/a11761",
            active: false,
        },
        {
            name:"KTTO Sacred Heart Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/ktto-sacred-heart-radio.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ssl-2.stream.miriamtech.net/sacredheartradio/hidden",
            active: false,
        },
        {
            name:"WSQM 90.9 Catholic Radio Indy",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wsqm-90.9-catholic-radio-indy.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ice8.securenetsystems.net/WSPMFM",
            active: false,
        },
        {
            name:"Radio Santa Eulalia",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radio-santa-eulalia.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream9.mexiserver.com:8326/stream",
            active: false,
        },
        {
            name:"KJWM Spirit Catholic Radio 91.5 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kjwm-spirit-catholic-radio-91.5-fm.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ice7.securenetsystems.net/KVSS",
            active: false,
        },
         {
            name:"RTVEmmaus Spanish",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/rtvemmaus-spanish.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://server7.servistreaming.com/proxy/rtvemaus?mp=%2Fstream",
            active: false,
        },
         {
            name:"WSPM Catholic Radio Indy 89.1",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wspm-catholic-radio-indy-89.1.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice8.securenetsystems.net/WSPMFM",
            active: false,
        },
        {
            name:"La Super Exclusiva HD",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/la-super-exclusiva-hd.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radios.sonicp.com:7012/;",
            active: false,
        },
        {
            name:"WPMW Radio CorMariae 88.5 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wpmw-radio-cormariae-88.5-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice23.securenetsystems.net/WPMWRCM",
            active: false,
        },
        {
            name:"KYTR Sacred Heart Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kytr-sacred-heart-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sacredheartradio.miriamtech.com:8000/hidden",
            active: false,
        },
        {
            name:"A los Pies de Cristo Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/a-los-pies-de-cristo-radio.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream-48.zeno.fm/qbq1k62b47zuv",
            active: false,
        },
        {
            name:"The Station of the Cross - Spanish",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/the-station-of-the-cross-spanish.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://hfc.streamguys1.com/icatholicradio",
            active: false,
        },
        {
            name:"WMTB 89.9 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wmtb-89.9-fm.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://50.207.162.63:81/broadwavehigh.mp3",
            active: false,
        },
        {
            name:"WFJS Domestic Church 1260",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wfjs-domestic-church-1260.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ic1.sslstream.com/dcm-ir",
            active: false,
        },
        {
            name:"KUFR 91.7 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kufr-91.7-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ais-sa3.cdnstream1.com/2641_64.aac",
            active: false,
        },
        {
            name:"WJTA Holy Family Radio 88.9 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wjta-holy-family-radio-88.9-fm.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://12.bteradio.com:8300/WJTA",
            active: false,
        },
        {
            name:"WPOG 710 AM and WWOS 91.1",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wpog-710-am-wwos-91.1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://shout2.brnstream.com:8004/;",
            active: false,
        },
        {
            name:"KVDM Divine Mercy Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kvdm-divine-mercy-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice41.securenetsystems.net/KMDG",
            active: false,
        },
        {
            name:"Sound Radio WPAE KPAE",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/sound-radio-wpae-kpae.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://74.82.59.197:8107/stream",
            active: false,
        },
        {
            name:"Stereo Revelacion Divina",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/stereo-revelacion-divina.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radiogetsemani.net:8131/stream",
            active: false,
        },
         {
            name:"WGUA-LP 98.1 FM Radio Catolica",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wgua-lp-98.1-fm-radio-catolica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://68.235.37.11:10002/;stream.mp3",
            active: false,
        },
         {
            name:"Real Presence Radio Network",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2022/09/real-presence-radio-network-150.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ssl-1.stream.miriamtech.net/realpresence/kwtl",
            active: false,
        },
         {
            name:"KBLE Sacred Heart Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kble-sacred-heart-radio.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sacredheartradio.stream.miriamtech.net:8000/hidden",
            active: false,
        },
         {
            name:"KJMA 89.7 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kjma-89.7-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://grn-stream-01.miriamtech.net:8000/KATH910AM.mp3",
            active: false,
        },
        {
            name:"WEWN Worldwide Catholic Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wewn.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ewtn-ice.streamguys1.com/english-aac",
            active: false,
        },
        {
            name:"Radio Apostol New Jersey",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radio-apostol-new-jersey.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream-39.zeno.fm/41xw7aq6vrquv",
            active: false,
        },
        {
            name:"WTJW-LP 93.1",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wtjw-lp-93.1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://dal-jcr-stream-1.neighborhoodca.com:8000/WTJW",
            active: false,
        },
        {
            name:"KLFT 90.5 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/klft-90.5-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice6.securenetsystems.net/KLFT",
            active: false,
        },
        {
            name:"Alfareros FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/alfareros-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream-40.zeno.fm/0etap8t704zuv",
            active: false,
        },
        {
            name:"WNGL Archangel Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wngl-archangel-radio-1410-am.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice41.securenetsystems.net/WNGL",
            active: false,
        },
        {
            name:"WCKW 1010 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wckw-1010-am.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://covenantnet.stream.miriamtech.net:8000/stream",
            active: false,
        },
        {
            name:"WRDF Redeemer Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wrdf-redeemer-radio.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://tektite.streamguys1.com:5300/live2",
            active: false,
        },
        {
            name:"KMMK 88.7 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kmmk-88.7-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://stream.kcrd-fm.org:8000/kmmk",
            active: false,
        },
        {
            name:"KEXS 1090 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kexs-1090-am.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice24.securenetsystems.net/CRN3",
            active: false,
        },
        {
            name:"KOLB Spirit Catholic Radio 88.3 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kolb-spirit-catholic-radio-88.3-fm.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice7.securenetsystems.net/KVSS",
            active: false,
        },
        {
            name:"89.3 WQPH",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/89.3-wqph.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://ic2.christiannetcast.com/wqph-fm",
            active: false,
        },
        {
            name:"KVSS Spirit Catholic Radio 102.7 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/spirit-catholic-radio.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice7.securenetsystems.net/KVSS",
            active: false,
        },
        {
            name:"WHIC The Station of the Cross",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/whic-the-station-of-the-cross.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://hfc.streamguys1.com/icatholicradio",
            active: false,
        },
        {
            name:"WJMJ Catholic Radio 88.9",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wjmj-catholic-radio-88.9.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://www.ophanim.net:7760/;",
            active: false,
        },
        {
            name:"Eastern Catholic Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/eastern-catholic-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ais-edge09-live365-dal02.cdnstream.com/a79728",
            active: false,
        },
        {
            name:"KCVV Radio Santisimo Sacramento 1240 AM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kcvv-radio-santisimo-sacramento-1240-am.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://santissimo.stream.miriamtech.net:8000/kcvv",
            active: false,
        },
        {
            name:"WBPL-LP Wilmington 92.7 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wbpl-lp-wilmington-catholic-radio-92.7-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://greg1.radioca.st/live",
            active: false,
        },
        {
            name:"KTYM ESNE 1460 AM - El Sembrador Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/ktym-esne-1460-am-el-sembrador-radio-catolica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://secure1.reliastream.com/esne-radio-guadalajara/;",
            active: false,
        },
        {
            name:"KBUP Sacred Heart Radio",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kbup-sacred-heart-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://sacredheartradio.miriamtech.com:8000/hidden",
            active: false,
        },
        {
            name:"KFJS Spirit Catholic Radio 90.1 FM",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/kfjs-spirit-catholic-radio-90.1-fm.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ice7.securenetsystems.net/KVSS",
            active: false,
        },
         {
            name:"WMET 1160 - Guadalupe Radio Network",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/wmet-1160-guadalupe-radio-network.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://grn-stream-01.miriamtech.net:8000/WMET1160AM.mp3",
            active: false,
        },
         {
            name:"Radio Fe Y Esperanza",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radio-fe-y-esperanza.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rss5.domint.net:8258/;stream.mp3",
            active: false,
        },
         {
            name:"Radio Jesucristo TV",
            artist: "Catholic Radios",
            cover: "https://manuappshome.files.wordpress.com/2020/12/radio-jesucristo-tv.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream-54.zeno.fm/87znwsv1kkeuv",
            active: false,
        },
    ];
}

export default chillHop;

