import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Otaku Music Radio",
            artist: "Otaku Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/otaku-music-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://kathy.torontocast.com:2880/1.mp3",
            active: true,
        },
        {
            name:"Radio Free Otaku",
            artist: "Otaku Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radio-free-otaku.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://streaming.radio.co/s8267e5edc/listen",
            active: false,
        },
        {
            name:"Otaku no Radio",
            artist: "Otaku Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/otaku-no-radio.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://radio.otakunopodcast.com:8000/otakunoradio",
            active: false,
        },
        {
            name:"Radio Otakus Dream",
            artist: "Otaku Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radio-otakus-dream-en-tunein.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://serv.1fm.me:8004/;",
            active: false,
        },
        {
            name:"Dominacion-CL",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/dominacion-cl.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://centova.audiostreaming.cl:8024/stream",
            active: false,
        },
        {
            name:"JetixBase-FM",
            artist: "Pop-Techno",
            cover: "https://manuappshome.files.wordpress.com/2019/11/jetixbase-fm-pop-techno.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://shirushiko-radio.anineko.online:8020/radio.mp3",
            active: false,
        },
        {
            name:"J-Pop Project Radio",
            artist: "J-Pop",
            cover: "https://manuappshome.files.wordpress.com/2019/11/j-pop-project-radio-mc3basica-asic3a1tica-pop.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "http://bluford.torontocast.com:8085/stream/;",
            active: false,
        },
        {
            name:"J-Pop Powerplay",
            artist: "J-Pop",
            cover: "https://manuappshome.files.wordpress.com/2019/11/j-pop-powerplay-pop.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://kathy.torontocast.com:3560/stream/1/",
            active: false,
        },        
         {
            name:"J-Idols Project Radio",
            artist: "J-Pop",
            cover: "https://manuappshome.files.wordpress.com/2019/11/j-idols-project-radio-all-japanese-idols-pop-mc3basica-asic3a1tica1.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://bluford.torontocast.com:8081/stream/;",
            active: false,
        },
        {
            name:"Japanimradio Fm",
            artist: "J-Pop",
            cover: "https://manuappshome.files.wordpress.com/2019/11/japanimradio-fm-pop-rock.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://japanimradio.be:8000/stream",
            active: false,
        },
        {
            name:"Wave Anime Radio",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/wave-anime-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "http://s04.radio-tochka.com:5470/mount",
            active: false,
        },
        {
            name:"Radio Forever Anime",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radio-forever-anime.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "http://199.168.188.202:9310/;",
            active: false,
        },
        {
            name:"MEGA FORCE RADIO",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/mega-force-radio-ac3b1os-80-ac3b1os-90.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://megaforce.radioca.st/stream",
            active: false,
        },
        {
            name:"BaKaRadio Anime",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/bakaradio-anime.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://144.217.203.184:8398/;",
            active: false,
        },
        {
            name:"AnimeNfo Radio",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/animenfo-radio-mc3basica-asic3a1tica-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://node-27.zeno.fm/xwa8ckz7mzzuv.aac",
            active: false,
        },
        {
            name:"Radio MangAnime",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radio-manganime-ma-pelc3adculas-musicales-pop.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://radio.manganime.ma/istream.mp3",
            active: false,
        },
        {
            name:"Power 945",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/power-945-en-tunein.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "http://198.50.156.92:8439/stream",
            active: false,
        },
        {
            name:"Kibo Fm",
            artist: "Pop-Rock",
            cover: "https://manuappshome.files.wordpress.com/2019/11/kibo-fm-pop-rock.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://listen.kibo.fm:8000/kibofm",
            active: false,
        },
        {
            name:"91.8 The Fan",
            artist: "Pop Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/91-8-the-fan-mc3basicas-del-mundo-pop.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "http://198.27.80.154:8080/;",
            active: false,
        },
        {
            name:"Animeacademy",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/animeacademy-buscar-con-google.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://animeacademy.stream.laut.fm/animeacademy",
            active: false,
        },
        {
            name:"Kpop Replay",
            artist: "Pop Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/kpop-replay-pop-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://rosetta.shoutca.st:8325/stream/",
            active: false,
        },
        {
            name:"Anime Web Radio",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/anime-web-radio-en-tunein.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://radioanime.radioca.st/stream",
            active: false,
        },
         {
            name:"kawaii-music",
            artist: "Pop Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/kawaii-music-pop.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://kawaii-music.stream.laut.fm/kawaii-music",
            active: false,
        },
         {
            name:"Asia DREAM Radio - Japan Hits",
            artist: "J-Pop",
            cover: "https://manuappshome.files.wordpress.com/2019/11/asia-dream-radio-japan-hits.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://igor.torontocast.com:1025/;",
            active: false,
        },
        {
            name:"AnimeNexus",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/animenexus-.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://radio.animenexus.net:8000/animenexus",
            active: false,
        },
        {
            name:"Animu FM",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/animu-fm-.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://cast.animu.com.br:9006/stream",
            active: false,
        },
        {
            name:"Radiogalaxy",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radiogalaxy-anime-buscar-con-google.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radiogalaxy.stream.laut.fm/radiogalaxy",
            active: false,
        },
        {
            name:"AnimeRadio Berlin",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/animeradio-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stream.animeradio.de/animeradio.mp3",
            active: false,
        },
        {
            name:"Radio Anime 24",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radio-anime-24-en-tunein.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://91.232.4.33:7028/;",
            active: false,
        },
        {
            name:"Vocaloid Radio",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/vocaloid-radio-buscar-con-google.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://curiosity.shoutca.st:8019/128",
            active: false,
        },
        {
            name:"Animefm",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/animefm-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://animefm.stream.laut.fm/animefm",
            active: false,
        },
        {
            name:"Anison FM",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/anison-fm.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://pool.anison.fm:9000/AniSonFM(320)",
            active: false,
        },
        {
            name:"Ronin Radio",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/ronin-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://s3.radio.co/sff133d65b/listen",
            active: false,
        },
        {
            name:"Anime Stereo",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/anime-stereo-buscar-con-google.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://radioanime.radioca.st/stream/1/",
            active: false,
        },
        {
            name:"Radio Akiba",
            artist: "Pop Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/rc3a1dio-akiba-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stm24.srvstm.com:9526/stream/1/",
            active: false,
        },
        {
            name:"NAMI anime radio",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/nami-anime-radio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://radio2.flex.ru:8000/radionami",
            active: false,
        },
        {
            name:"R/a/dio",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/r-a-dio.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://relay0.r-a-d.io/main.mp3",
            active: false,
        },
         {
            name:"Radio AnimeNight",
            artist: "Anime Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/rc3a1dio-animenight-mc3basica-asic3a1tica.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://stm11.srvstm.com:8356/stream/1/",
            active: false,
        },
         {
            name:"Radio Nolife",
            artist: "Pop Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/radio-nolife-mc3basicas-del-mundo-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://nolife-radio.com:9000/stream",
            active: false,
        },
         {
            name:"Fluffylandrpg",
            artist: "Pop Music",
            cover: "https://manuappshome.files.wordpress.com/2019/11/fluffylandrpg-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://fluffylandrpg.stream.laut.fm/fluffylandrpg",
            active: false,
        },
         {
            name:"Zelina-s Mixed Bag of Showtunes",
            artist: "",
            cover: "https://manuappshome.files.wordpress.com/2019/11/zelina-s-mixed-bag-of-showtunes.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streamingv2.shoutcast.com/Zelina-sMixedBagofShowtunes",
            active: false,
        },
         {
            name:"HOTMIXRADIO Japan",
            artist: "J-Pop",
            cover: "https://manuappshome.files.wordpress.com/2019/11/hotmixradio-japan-pop.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://streaming.hotmixradio.fr/hotmixradio-japan-128.mp3",
            active: false,
        },
    ];
}

export default chillHop;

